research_task:
  description: >
    Search five news about {topic}
  expected_output: >
    A list of five news articles about {topic} with the title, url, image and snippet
  agent: researcher

reporting_task:
  description: >
    Review the news context you got from the research agent.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A summary reporting for each one of the news articles founded by the research agent. Make sure you have the title, summary, url and the image.
    Formatted as markdown without '```'
  agent: reporting_analyst
