generate_joke_task:
  description: >
    generate 10 chuck norris jokes.
  expected_output: >
    A list with 10 chuck norris jokes
  agent: chuck_norris_joke_generator

pick_joke_task:
  description: >
    Pick the best joke of a list of jokes.
  expected_output: >
    The best joke from the list of generated jokes by the chuck_norris_joke_generator.
  agent: chuck_norris_joke_picker
