research_task:
  description: >
    Search three news about {topic}
    The current time is {date}
  expected_output: >
    A list of three news articles about {topic} with the title, url and snippet
  agent: researcher

reporting_task:
  description: >
    Review the news context you got from the research agent.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A sumamry reporting for each one of the news articles founded by the research agent.
    Formatted as markdown without '```'
  agent: reporting_analyst
